### ISSUE TITLE
Update read me

### ISSUE THREAD

**Issue by austinankur** [mikemukul/test_repo_fork#2]
* Add more info about project
* Project guidelines

**Comment by mikemukul** [comment]
Added more information

**Comment by austinankur** [comment]
Read me file seems intact, 
We need to add project description

**Comment by mikemukul** [comment]
Added information about Testing Framework

**Comment by austinankur** [comment]
We reference issue id in commit message, so that it is easy to find which commit fixes this issue.
```
git commit -m "Your message, close #123"
```
Just like that.
